# Generated by Django 5.2.6 on 2025-09-14 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(help_text='رقم الهاتف مع رمز البلد (مثال: 966501234567)', max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='اسم العائلة')),
                ('is_active', models.BooleanField(default=True, help_text='يحدد ما إذا كان هذا المستخدم نشطًا أم لا', verbose_name='نشط')),
                ('is_admin', models.BooleanField(default=False, help_text='يحدد ما إذا كان المستخدم مشرفًا', verbose_name='مشرف')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الانضمام')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر تسجيل دخول')),
                ('device_token', models.TextField(blank=True, help_text='رمز Firebase للإشعارات', null=True, verbose_name='رمز الجهاز')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='المدينة')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='الرمز البريدي')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
                'db_table': 'users',
            },
        ),
    ]
