# Generated by Django 5.2.6 on 2025-10-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrder',
            fields=[
            ],
            options={
                'verbose_name': 'طلب جديد',
                'verbose_name_plural': 'الطلبات الجديدة',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='ProcessedOrder',
            fields=[
            ],
            options={
                'verbose_name': 'طلب معالج',
                'verbose_name_plural': 'الطلبات المعالجة',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الكوبون'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم الكوبون'),
        ),
    ]
