web: gunicorn ecom_project.wsgi:application --bind 0.0.0.0:$PORT --chdir backend
release: cd backend && python execute_sql.py && python manage.py migrate && python manage.py loaddata products/fixtures/coupons.json && python manage.py clear_cache && python manage.py collectstatic --no-input
