web: gunicorn ecom_project.wsgi:application --bind 0.0.0.0:$PORT --chdir backend
release: python ../execute_sql.py && python manage.py migrate --chdir backend && python ../create_test_coupon.py && python manage.py collectstatic --no-input --chdir backend
