# Generated by Django 5.2.6 on 2025-10-10 01:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإعلان')),
                ('description', models.TextField(blank=True, verbose_name='وصف الإعلان')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='صورة الإعلان')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='رابط صورة الإعلان (الخارجي)')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='رابط التوجيه')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الكوبون')),
                ('description', models.TextField(blank=True, verbose_name='وصف الكوبون')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'قيمة ثابتة')], default='percentage', max_length=10, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قيمة الخصم')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحد الأدنى للطلب')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحد الأقصى للخصم')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='عدد المرات التي يمكن استخدام الكوبون فيها (فارغ للعد غير المحدود)', null=True, verbose_name='حد الاستخدام')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الاستخدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'كوبون الخصم',
                'verbose_name_plural': 'كوبونات الخصم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('discount_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتوفرة')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, verbose_name='حد التنبيه للمخزون')),
                ('main_image', models.URLField(blank=True, null=True, verbose_name='رابط الصورة الرئيسية (ImgBB)')),
                ('image_2', models.URLField(blank=True, null=True, verbose_name='رابط الصورة الثانية (ImgBB)')),
                ('image_3', models.URLField(blank=True, null=True, verbose_name='رابط الصورة الثالثة (ImgBB)')),
                ('image_4', models.URLField(blank=True, null=True, verbose_name='رابط الصورة الرابعة (ImgBB)')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='العلامة التجارية')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='الموديل')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='اللون')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='المقاس')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الوزن (كجم)')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='الرابط')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='وصف SEO')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='الكلمات المفتاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='منتج مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, verbose_name='التعليق')),
                ('is_approved', models.BooleanField(default=True, verbose_name='معتمد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تقييم المنتج',
                'verbose_name_plural': 'تقييمات المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ المشاهدة')),
            ],
            options={
                'verbose_name': 'مشاهدة المنتج',
                'verbose_name_plural': 'مشاهدات المنتجات',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='صورة القسم')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='رابط صورة القسم (الخارجي)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='القسم الأب')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستخدام')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.coupon', verbose_name='الكوبون')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'استخدام الكوبون',
                'verbose_name_plural': 'استخدامات الكوبون',
                'ordering': ['-used_at'],
            },
        ),
    ]
