# Generated by Django 5.2.6 on 2025-10-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'قسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='الأقسام ذات الترتيب الأقل تظهر أولاً', verbose_name='ترتيب العرض'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='المنتجات ذات الترتيب الأقل تظهر أولاً', verbose_name='ترتيب العرض'),
        ),
    ]
