# Generated by Django 5.2.6 on 2025-10-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_change_discount_to_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='صورة الإعلان (قديمة - استخدم image_url بدلاً منها)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صورة الإعلان من ImgBB'),
        ),
    ]
