# Generated by Django 5.2.6 on 2025-10-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_make_banner_image_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_homepage',
            field=models.BooleanField(default=True, verbose_name='إظهار في الواجهة الرئيسية'),
        ),
    ]
