# Generated by Django 5.2.6 on 2025-10-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image_2_product_image_3_product_image_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='موديل المنتج'),
        ),
    ]
