# Generated by Django 5.2.6 on 2025-10-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='اللون'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=200, verbose_name='الأبعاد'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100, verbose_name='المادة'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='المقاس'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='فترة الضمان (بالشهور)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الوزن (كجم)'),
        ),
    ]
