# Generated by Django 5.2.6 on 2025-10-02 10:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_color_product_dimensions_product_material_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'إعلان', 'verbose_name_plural': 'الإعلانات'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'تقييم المنتج', 'verbose_name_plural': 'تقييمات المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productview',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'مشاهدة المنتج', 'verbose_name_plural': 'مشاهدات المنتجات'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='order',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_period',
        ),
        migrations.RemoveField(
            model_name='productview',
            name='created_at',
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الإعلان'),
        ),
        migrations.AddField(
            model_name='banner',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صورة الإعلان (الخارجي)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='link_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط التوجيه'),
        ),
        migrations.AddField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='products.product', verbose_name='المنتج المرتبط'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='الرابط'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='الكلمات المفتاحية'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='معتمد'),
        ),
        migrations.AddField(
            model_name='productview',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='معلومات المتصفح'),
        ),
        migrations.AddField(
            model_name='productview',
            name='viewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ المشاهدة'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='صورة الإعلان'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الإعلان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة الثانية (ImgBB)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة الثالثة (ImgBB)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة الرابعة (ImgBB)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, verbose_name='حد التنبيه للمخزون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة الرئيسية (ImgBB)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='وصف SEO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية المتوفرة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الوزن (كجم)'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(blank=True, verbose_name='التعليق'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='productview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='products_pr_is_feat_a1ecf6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
    ]
