# Generated by Django 5.2.6 on 2025-10-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
