# Generated by Django 5.2.6 on 2025-10-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='governorate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة'),
        ),
    ]
