# Generated by Django 5.2.6 on 2025-10-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
    ]
