# Generated by Django 5.2.6 on 2025-09-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صورة الإعلان (الخارجي)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='صورة الإعلان'),
        ),
    ]
