# Generated by Django 5.2.6 on 2025-09-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_banner_image_url_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صورة القسم (الخارجي)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='صورة القسم'),
        ),
    ]
